---
  
- name: mkdir /tmp/promtail
  ansible.builtin.file:
    path: /tmp/promtail
    state: directory
    mode: 0755

- name: unpack promtail
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm' }}.zip"
    dest: /tmp/promtail
    remote_src: yes

- name: copy promtail binary to $PATH
  ansible.builtin.copy:
    src: /tmp/promtail/promtail-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm' }}
    dest: /usr/local/bin/promtail
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  notify: restart promtail

- name: rm -r /tmp/promtail
  ansible.builtin.file:
    path: /tmp/promtail
    state: absent

