---

- name: check promtail is installed
  ansible.builtin.command: promtail --version
  register: promtail_installed
  failed_when: no
  changed_when: no

- ansible.builtin.import_tasks: binary.yml
  # DISCLAIMER: fix for https://github.com/grafana/loki/issues/4174
  vars:
    promtail_sanitized_version: "{{ promtail_installed.stdout_lines[0].split(' ')[2] if promtail_installed.stdout_lines[0].split(' ')[2] != '' else '2.3.0' }}"
  when: promtail_installed.rc != 0 or promtail_sanitized_version is version(promtail_version, '<')

- name: mkdir /etc/promtail
  ansible.builtin.file:
    path: /etc/promtail
    state: directory
    mode: 0750
    owner: root
    group: root

- name: copy config.yml
  ansible.builtin.template:
    src: config.yml
    dest: /etc/promtail/config.yml
    mode: 0640
    owner: root
    group: root
  notify: restart promtail

- name: copy unit file
  ansible.builtin.template:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
    mode: 0644
    owner: root
    group: root
  notify: restart promtail

- name: enable promtail
  ansible.builtin.systemd:
    name: promtail.service
    enabled: yes
